In [12]:
from core import Cell, World, COLORS
import numpy as np 
import time 

In [ ]:
class Cell: 
    """ 
    Cell is a living one. it's born with name, age, color, face(direction).
    1. born: born with a given world
    2. die: die itself
    3. move: move somewhere
       """
    def __init__(self, world: World) -> None:
        self.world = world
        self.alive = False 
        self.current_location = None 
        self.color = None 
        self.age = 0
        self.born_time = None
        self.face = None 

        available_space = self.get_space()
        if available_space is not None:
            self.born(available_space)
        else:
            raise("No available space")

    def born(self, available_space) -> None:
        self.world.spaces[available_space[0], available_space[1]] = self 
        self.world.lifes.append(self)
        self.world.lifes_ever += 1 
        
        self.alive = True
        self.current_location = available_space
        self.born_time = time.time()
        self.face = np.random.choice([0, 1, 2, 3])    # clock wise: front=0 -> right=1 -> back=2 -> left=3
        self.name = f"Cell_{self.world.lifes_ever}"
        self.color = COLORS[np.random.choice(len(COLORS))] 

    def die(self) -> None:
        if self.alive: 
            location = np.where(self.world.spaces == self)
            self.world.spaces[location[0], location[1]] = 0
            self.alive = False
            self.color = None 
        else:
            print("Cell is already dead")

    def get_space(self) -> None | np.ndarray:
        available_spaces = self.world.get_avialable_spaces()
        len_available_space = len(available_spaces)
        if len_available_space == 0:
            return None
        else:
            location = np.random.choice(len_available_space)
            return available_spaces[location]
            
    def __repr__(self):
        if self.alive:
            return f"{self.name}" 
        else: 
            return "Unborn Cell"

    # Aging system
    def aging(self) -> None:
        current_time = time.time()
        elapsed_time = np.round(current_time - self.born_time, 2)

        if self.alive and elapsed_time % 5:
            self.age += 1 
            self.color = self.color * 0.9

            if self.age > 10:
                self.die()
    
    def search_to_move(self):
        """
        Try to move with face(direction), get new location to move.
        There's some rules. It cant' move beyond the world mpa. So, the widht and height of the world.
        Secondly, it should have a logic to bump with other cells.
        """
        if self.face == 0:  # front
            new_location = self.current_location + np.array([-1, 0])
        elif self.face == 1:    # right
            new_location = self.current_location + np.array([0, 1])
        elif self.face == 2:    # back
            new_location = self.current_location + np.array([1, 0])
        elif self.face == 3:    # left
            new_location = self.current_location + np.array([0, -1]) 
        else:
            raise ValueError("Unknown face value. It must be {0, 1, 2, 3}")
        
        return new_location

        """ if 0 <= new_location[0] < self.world.HEIGHT and 0 <= new_location[1] < self.world.WIDTH:
            # print(f"Can move to {new_location}")

            # if move to new location, then update to self.world spaces. 1.remove past location, 2.add new location
            self.world.spaces = np.where(self.world.spaces == self, 0, self.world.spaces)
            self.world.spaces[new_location[0], new_location[1]] = self

            return new_location
        else:
            print(f"Impossible to move to {new_location}. Please turn your face.")
            self.turn_face()
            return self.current_location """
        
    def ask_next_move(self):
        """ 
        1. Cell sends a location of next move to World.
        2. World respond to the cell, what's in the location it asked.
        """
        new_location = self.search_to_move()
        if 0 <= new_location[0] < self.world.HEIGHT and 0 <= new_location[1] < self.world.WIDTH:
            next_step = self.world.spaces[new_location[0], new_location[1]] 

            print(f"search_to_move: {self.search_to_move()}")
            print(f"next_step: {next_step}")

            if next_step == 0: # 0 means empty, so free to move
                self.move(new_location)
        else:
            self.turn_face()
            print("Not available to move next")

    def move(self, new_location):
        self.current_location = new_location

        # Update world spaces info
        self.world.spaces = np.where(self.world.spaces == self, 0, self.world.spaces)
        self.world.spaces[new_location[0], new_location[1]] = self



    def turn_face(self):
        # random choice
        new_face = np.where(self.face != [0, 1, 2, 3])[0] # except its previous face
        self.face = np.random.choice(new_face)

In [95]:
world = World()
c1 = Cell(world)
c2 = Cell(world)


In [149]:
world.spaces

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, Cell_2, 0],
       [0, Cell_1, 0, 0]], dtype=object)

In [150]:
c1.face 

1

In [151]:
c1.current_location

array([3, 1])

In [152]:
c1.ask_next_move() 

search_to_move: [3 2]
next_step: 0


In [ ]:
c1.ask_ne

search_to_move: [1 1]
0


In [ ]:

c2 

Cell_2

In [50]:
world.spaces 

array([[0, 0, 0, '0-3'],
       [0, 0, 0, 0],
       [0, 0, Cell_2, Cell_1],
       ['@', 0, 0, '@']], dtype=object)

In [153]:
[f for f in [0, 1, 2, 3] if f != 0]

[1, 2, 3]

In [185]:
 l = [0, 1, 2, 3]

In [186]:
l.remove(3)

In [192]:
a = [0, 1, 2, 3].remove(0)

In [189]:
np.random.choice([0, 1, 2, 3].remove(0))

ValueError: a must be 1-dimensional or an integer