In [2]:
import numpy as np  
import pygame 
import time 

""" 
=====================================================================================
Logic 
1. World is created with spaces.
2. Cell is created with world.
3. Cell is born in the world.
4. Cell dies in the world.
5. Cell can be born in the world.
"""

class World: 
    def __init__(self):
        self.HEIGHT = 5 
        self.WIDTH = 3 

        self.spaces = np.zeros((self.HEIGHT, self.WIDTH), dtype=Cell)

        self.lifes_ever = 0
        self.lifes = []

    def get_avialable_spaces(self) -> np.ndarray[np.ndarray[int], np.ndarray[int]]:
        return np.stack(np.where(self.spaces == 0), axis=1)


class Cell: 
    def __init__(self, world: World):
        self.world = world
        self.alive = False 
        self.current_location = None 
        self.color = None 
        self.age = 0
        self.born_time = None
        self.born()
        self.face = np.random.choice([0, 1, 2, 3])    # clock wise: front=0 -> right=1 -> back=2 -> left=3

    def born(self):
        location = self.get_space()
        if location is None:
            print("No available space")
        else:
            self.world.lifes_ever += 1 
            self.name = f"Cell_{self.world.lifes_ever}"
            self.born_time = time.time()

            self.world.spaces[location[0], location[1]] = self 
            self.current_location = location
            self.alive = True
            self.color = COLORS[np.random.choice(len(COLORS))]
            self.world.lifes.append(self)
    
    def die(self):
        if self.alive: 
            location = np.where(self.world.spaces == self)
            self.world.spaces[location[0], location[1]] = 0
            self.alive = False
            self.color = None 
        else:
            print("Cell is already dead")


    def get_space(self):
        available_spaces = self.world.get_avialable_spaces()
        len_available_space = len(available_spaces)
        if len_available_space == 0:
            return None
        else:
            location = np.random.choice(len_available_space)
            return available_spaces[location]
            
    def __repr__(self):
        if self.alive:
            return f"{self.name}" 
        else: 
            return "Unborn Cell"

    # Aging system
    def aging(self):
        current_time = time.time()
        elapsed_time = np.round(current_time - self.born_time, 2)

        if self.alive and elapsed_time % 5:
            self.age += 1 
            self.color = self.color * 0.9

            if self.age > 10:
                self.die()
    
    def search_to_move(self):
        if self.face == 0:  # front
            new_location = self.current_location + np.array([-1, 0])
        elif self.face == 1:    # right
            new_location = self.current_location + np.array([0, 1])
        elif self.face == 2:    # back
            new_location = self.current_location + np.array([1, 0])
        elif self.face == 3:    # left
            new_location = self.current_location + np.array([0, -1])
        else:
            raise ValueError("Unknown face value. It must be {0, 1, 2, 3}")
        
        if 0 <= new_location[0] < world.HEIGHT and 0 <= new_location[1] < world.WIDTH:
            print(f"Can move to {new_location}")
            return new_location
        else:
            print(f"Impossible to move to {new_location}. Please turn your face.")
            self.turn_face()
            return self.current_location
        
    def move(self):
        self.current_location = self.search_to_move()

    def turn_face(self):
        if self.face == 3:
            self.face = 0
        else: 
            self.face += 1
            
""" 
=====================================================================================
2. Rendering the world
"""

# pygame setup
DISPLAY_WIDTH = 800
HEIGHT = 600



#set up the colors
WHITE = np.array([255, 255, 255])
YELLOW = np.array([255, 255, 0])
RED = np.array([255, 0, 0])
BLUE = np.array([0, 0, 255])
GREEN = np.array([0, 255, 0])
BLACK = np.array([0, 0, 0])
ORANGE = np.array([255, 128, 0])
PURPLE = np.array([128,0,128])

COLORS = [RED, BLUE, GREEN, ORANGE, PURPLE]


def render_world(world: World):
    grid_color = WHITE 

    tile_width = DISPLAY_WIDTH // world.WIDTH
    tile_height = HEIGHT // world.HEIGHT

    for x in range(0, DISPLAY_WIDTH, tile_width):
        pygame.draw.line(screen, grid_color, (x, 0), (x, HEIGHT))
    for y in range(0, HEIGHT, tile_height):
        pygame.draw.line(screen, grid_color, (0, y), (DISPLAY_WIDTH, y))


def render_cell(cell: Cell, world: World, color=RED):
    width = DISPLAY_WIDTH // world.WIDTH
    height = HEIGHT // world.HEIGHT

    if cell.alive:
        x, y = cell.current_location
        x_position = x * width
        y_position = y * height

        rect = pygame.Rect(x_position, y_position, width, height) # (x, y, width, height)

        pygame.draw.rect(screen, color, rect)
        

world = World()

c1 = Cell(world)
# c2 = Cell(world)
# c3 = Cell(world)
# c4 = Cell(world)

t = time.time()

In [3]:
world.spaces


array([[0, 0, 0],
       [0, Cell_1, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=object)

In [4]:
world.get_avialable_spaces()

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2],
       [3, 0],
       [3, 1],
       [3, 2],
       [4, 0],
       [4, 1],
       [4, 2]])

In [5]:
c1.current_location 

array([1, 1])

In [6]:
c1.face 

3

In [7]:
c1.move()

Can move to [1 0]


In [8]:
c1.current_location = c1.move()

Impossible to move to [ 1 -1]. Please turn your face.


In [9]:
foods = []

foods.append("A")

In [14]:
foods.remove("A")

ValueError: list.remove(x): x not in list

In [12]:
foods.append("B")

In [13]:
foods 

['B']

In [16]:
a = np.array([0, 1, 2, 3])
a 

array([0, 1, 2, 3])

In [22]:
np.where(a !=0)[0]

array([1, 2, 3])

In [47]:
world.spaces[0][0] = '@'

In [ ]:
c1 = world.spaces[1][1]
c1

Cell_1

In [42]:
type(c1.name)

str

In [61]:
world.spaces = np.where(world.spaces ==  c1, 0, world.spaces)

In [67]:
world.spaces

array([['@', Cell_2, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=object)

In [65]:
c1 = Cell(world)

In [69]:
world.spaces[c1.current_location[0], c1.current_location[1]]

Cell_2